[versions]
opencv = "4.9.0-1.5.10"
tesseract = "5.3.4-1.5.10"

[libraries]
cache-core = { module = "org.springframework.boot:spring-boot-starter-cache" }
cache-caffeine = { module = "com.github.ben-manes.caffeine:caffeine" }
opencv-platform = { module = "org.bytedeco:opencv-platform", version.ref = "opencv" }
tesseract-platform = { module = "org.bytedeco:tesseract-platform", version.ref = "tesseract" }

[bundles]
spring-cache = ["cache-core", "cache-caffeine"]
bytedeco = ["opencv-platform", "tesseract-platform"]