server:
  servlet:
    encoding:
      charset: UTF-8
  error:
    whitelabel:
      enabled: false
  port: 2627

spring:
  profiles:
    include:
      - custom
      - database
    active: prod
  mvc:
    converters:
      preferred-json-mapper: jackson
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        keep-alive: 60s
        queue-capacity: 100
      thread-name-prefix: COCRTask-
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      max-request-size: 40MB
      max-file-size: 32MB

liteflow:
  enable: true
  print-banner: false
  parse-mode: parse_all_on_start

logging:
  pattern:
    dateformat:
      dd-MM-yyyy HH:mm:ss.SSS
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 4096KB
      file-name-pattern: ./data/logs/%d{yyyy-MM-dd}.%i.log
