cocr:
  info:
    app-license: app.license
    artifact: project.artifactId
    build-timestamp: maven.build.timestamp
    group: project.groupId
    java-version: java.version
    name: project.name
    spring-boot-version: project.parent.version
    version: project.version
  cors:
    allowed-header:
      - '*'
    allowed-methods:
      - GET
      - OPTIONS
      - PATCH
      - POST
      - DELETE
    origin-patterns:
      - http://localhost:[*]
  tesseract:
    ocr-engine-mode: OEM_LSTM_ONLY
    page-seg-mode: PSM_SINGLE_LINE
    language:
      - eng
      - chi_sim
    vectors:
      - name: chop_enable
        value: 'true'
      - name: language_model_ngram_on
        value: 'false'
      - name: tessedit_char_blacklist
        value: <>《》丨~|\/`^'-_§丶ˇ〆‰⺄⺈⺌⺗⺶⻗丷勹宀癶艹刂彳巛亻卩犭匚灬纟钅耂冫丿冖凵彡氵饣礻忄厶扌囗亠讠衤乚廴爫乛夂豸𥫗丬辶阝ノ
      - name: preserve_interword_spaces
        value: 'true'
      - name: unrecognised_char
        value: ' '
      - name: textord_force_make_prop_words
        value: 'false'
      - name: edges_max_children_per_outline
        value: '40'
  ocr:
    min-black-pixel-threshold: 0.01
    max-white-pixel-threshold: 99.97
    ssim-threshold: 0.95
    invert-threshold: 0
