spring:
  datasource:
    url: jdbc:h2:file:./data/cocr
    username: sa
    password: passwd
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  exposed:
    show-sql: false